export const PAUSE_MENU_BINDINGS = [
  { label: 'Move', value: 'WASD' },
  { label: 'Jump', value: 'Space' },
  { label: 'Run', value: 'Shift' },
  { label: 'Crouch', value: 'C' },
  { label: 'Fly Toggle', value: 'V' },
  { label: 'Log Pos', value: 'J' },
  { label: 'Save Marker', value: 'K' },
  { label: 'Dump Markers', value: 'L' },
  { label: 'Collision Debug', value: 'B' },
  { label: 'Fire', value: 'Left click' },
  { label: 'Scope', value: 'Right click' },
  { label: 'Weapons', value: '1 rifle, 2 pistol, 3 knife, 4 sniper, 5 bomb, 6 utility' },
  { label: 'Pause', value: 'Escape' },
];
