export const NETCODE_SIMULATION_RATE = 60;
export const NETCODE_SIMULATION_STEP = 1 / NETCODE_SIMULATION_RATE;
export const NETCODE_INPUT_SEND_RATE = 30;
export const NETCODE_INPUT_SEND_INTERVAL = 1 / NETCODE_INPUT_SEND_RATE;
export const NETCODE_REMOTE_INTERPOLATION_DELAY_MS = 67;
export const NETCODE_MAX_REMOTE_SNAPSHOTS = 20;
export const NETCODE_LAG_COMPENSATION_MAX_REWIND_MS = 250;
export const NETCODE_SERVER_HITBOX_HISTORY_MS = 300;
