export const NETCODE_SIMULATION_RATE = 60;
export const NETCODE_SIMULATION_STEP = 1 / NETCODE_SIMULATION_RATE;
export const NETCODE_INPUT_SEND_RATE = 20;
export const NETCODE_INPUT_SEND_INTERVAL = 1 / NETCODE_INPUT_SEND_RATE;
export const NETCODE_REMOTE_INTERPOLATION_DELAY_MS = 100;
export const NETCODE_MAX_REMOTE_SNAPSHOTS = 20;
