export const PLAYER_MAX_HEALTH = 100;
export const PLAYER_RESPAWN_DELAY_MS = 2000;

export const SHARED_WEAPON_DATA = {
  rifle: {
    key: 'rifle',
    damage: 5,
    damageByHitZone: {
      head: 100,
      body: 32,
      arms: 24,
      legs: 24,
    },
    fireInterval: 1 / 8,
    automatic: true,
    canScope: true,
    hipfireSpread: 0,
    airborneSpread: 0.035,
    movementSpeedMultiplier: 1,
    walkSpeedFactor: 0.5,
    magazineSize: 30,
    reserveAmmo: 90,
    reloadTime: 2.45,
    visualRecoil: {
      warmupShots: 2,
      initialPitch: 0.034,
      maxPitch: 0.19,
      shoulderShots: 3,
      shoulderPitch: 0.047,
      riseSharpness: 4.05,
      shotResetDelay: 0.22,
      sprayResetDelay: 0.32,
      recoveryFast: 16,
      recoverySlow: 6.5,
      maxShots: 20,
      recoveryShotPenaltyShots: 18,
      recoveryShotPenaltyFactor: 0.24,
      aimPullStartShots: 9,
      aimPullYawMax: 0.014,
    },
    sprayRecoil: {
      warmupShots: 2,
      maxShots: 16,
      initialOffsetY: 0.019,
      maxOffsetY: 0.125,
      shoulderShots: 4,
      shoulderOffsetY: 0.024,
      riseSharpness: 2.6,
      horizontalStartShots: 6,
      maxOffsetX: 0.016,
      horizontalExponent: 1.2,
      shotResetDelay: 0.18,
      sprayResetDelay: 0.22,
    },
  },
  pistol: {
    key: 'pistol',
    damage: 14,
    fireInterval: 0.22,
    semiAutoInputBuffer: 0.08,
    automatic: false,
    canScope: true,
    hipfireSpread: 0.002,
    airborneSpread: 0.024,
    movementSpeedMultiplier: 1.04,
    walkSpeedFactor: 0.5,
    magazineSize: 12,
    reserveAmmo: 36,
    reloadTime: 1.9,
    visualRecoil: {
      warmupShots: 1,
      initialPitch: 0.018,
      maxPitch: 0.075,
      shoulderShots: 3,
      shoulderPitch: 0.03,
      riseSharpness: 2.2,
      shotResetDelay: 0.16,
      sprayResetDelay: 0.08,
      recoveryFast: 18,
      recoverySlow: 9,
      maxShots: 6,
      recoveryShotPenaltyShots: 6,
      recoveryShotPenaltyFactor: 0.55,
      aimPullStartShots: 3,
      aimPullYawMax: 0.004,
    },
    sprayRecoil: {
      warmupShots: 1,
      maxShots: 6,
      initialOffsetY: 0.008,
      maxOffsetY: 0.03,
      shoulderShots: 3,
      shoulderOffsetY: 0.014,
      riseSharpness: 1.9,
      horizontalStartShots: 3,
      maxOffsetX: 0.015,
      horizontalExponent: 1.79,
      shotResetDelay: 0.33,
      sprayResetDelay: 0.06,
    },
  },
  sniper: {
    key: 'sniper',
    damage: 100,
    damageByHitZone: {
      head: 100,
      body: 100,
      arms: 100,
      legs: 100,
    },
    fireInterval: 1.25,
    equipDuration: 1.0,
    automatic: false,
    canScope: true,
    hipfireSpread: 0.05,
    movingSpread: 0.12,
    movingSpreadSpeedThreshold: 1.5,
    scopeAccuracyGraceDuration: 0.35,
    scopeTransitionSpread: 0.05,
    zoomFovLevels: [18, 8],
    movementSpeedMultiplier: 0.96,
    walkSpeedFactor: 0.5,
    magazineSize: 5,
    reserveAmmo: 20,
    reloadTime: 3.1,
  },
  knife: {
    key: 'knife',
    damage: 25,
    meleeRange: 2.2,
    fireInterval: 0.42,
    automatic: false,
    canScope: false,
    hipfireSpread: 0,
    movementSpeedMultiplier: 1.25,
    walkSpeedFactor: 0.6,
    magazineSize: 0,
    reserveAmmo: 0,
    reloadTime: 0,
  },
  bomb: {
    key: 'bomb',
    damage: 0,
    fireInterval: 0.5,
    automatic: false,
    canScope: false,
    canFire: false,
    hipfireSpread: 0,
    movementSpeedMultiplier: 1,
    walkSpeedFactor: 0.5,
    magazineSize: 0,
    reserveAmmo: 0,
    reloadTime: 0,
  },
};

export function getSharedWeaponData(weaponKey) {
  return SHARED_WEAPON_DATA[weaponKey] ?? null;
}
